---

- name: docker
  include: docker.yml

- name: install bzip2
  yum:
    name: bzip2
    state: installed

- name: verify if blender archive is present
  stat:
    path: "/home/{{ ansible_user }}/blender-2.79b-linux-glibc219-x86_64.tar.bz2"
  register: blender_archive

- name: wget blender
  get_url:
    url: https://download.blender.org/release/Blender2.79/blender-2.79b-linux-glibc219-x86_64.tar.bz2
    dest: "/home/{{ ansible_user }}/"
  when: blender_archive.stat.exists == false

  #- name: build chess-fracture docker images
  #  docker_image:
  #    path: "/home/{{ ansible_user }}/docker-chess-fracture/blender"
  #    name: chess-fracture
  #  become_user: "{{ ansible_user }}"
  #

- name: unarchive blender
  unarchive:
    remote_src: yes
    src: "/home/{{ ansible_user }}/blender-2.79b-linux-glibc219-x86_64.tar.bz2"
    dest: "/home/{{ ansible_user }}/"

- name: verify if get-pip is present
  stat:
    path: "/home/{{ ansible_user }}/blender-2.79b-linux-glibc219-x86_64/get-pip.py"
  register: get_pip

- name: wget get-pip
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: "/home/{{ ansible_user }}/blender-2.79b-linux-glibc219-x86_64/"
  when: get_pip.stat.exists == false

- name: install pip
  command: 2.79/python/bin/python3.5m get-pip.py
  args:
    chdir: "/home/{{ ansible_user }}/blender-2.79b-linux-glibc219-x86_64/"
    creates: "/home/{{ ansible_user }}/blender-2.79b-linux-glibc219-x86_64/2.79/python/bin/pip"

- name: install requests python-chess
  command: 2.79/python/bin/python3.5m -m pip install requests python-chess
  args:
    chdir: "/home/{{ ansible_user }}/blender-2.79b-linux-glibc219-x86_64/"
    creates:
      - "/home/{{ ansible_user }}/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/requests"
      - "/home/{{ ansible_user }}/blender-2.79b-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/chess"
