---

- name: docker
  include: docker.yml

- name: verify if blender archive is present
  stat:
    path: "/home/{{ ansible_user }}/docker-chess-fracture/blender/blender-2.79b-linux-glibc219-x86_64.tar.bz2"
  register: blender_archive

- name: wget blender
  get_url:
    url: https://download.blender.org/release/Blender2.79/blender-2.79b-linux-glibc219-x86_64.tar.bz2
    dest: "/home/{{ ansible_user }}/docker-chess-fracture/blender/"
  when: blender_archive.stat.exists == false

- name: build chess-fracture docker images
  docker_image:
    path: "/home/{{ ansible_user }}/docker-chess-fracture/blender"
    name: chess-fracture
  become_user: "{{ ansible_user }}"

