---
# tasks file for docker-chess-fracture
- name: test connection
  ping:

- name: install requirements
  yum:
    name:
      - yum-utils
      - zip
      - xorg-x11-server-Xorg
      - xorg-x11-xauth
      - xorg-x11-server-utils
      - mesa-dri-drivers
      - git
      - python2-pip
      - gcc
      - openssl-devel

- name: sync files
  synchronize:
    src: "{{ playbook_dir }}/.."
    dest: "/home/{{ ansible_user }}/docker-chess-fracture"
  become_user: "{{ ansible_user }}"
  notify:
    - rebuild webapp

#- name: git clone http://github.com/tatref/docker-chess-fracture
#  git:
#    repo: 'http://github.com/tatref/docker-chess-fracture'
#    dest: "/home/{{ ansible_user }}/docker-chess-fracture"
#    #depth: 1
#  become_user: "{{ ansible_user }}"
#  notify:
#    - rebuild webapp


- name: turbovnc
  include: turbovnc.yml

- name: reverse proxy
  include: nginx.yml

- name: blender
  include: blender.yml

- name: webapp
  include: webapp.yml

