---

- name: add turbovnc repo
  yum_repository:
    name: TurboVNC
    description: TurboVNC official RPMs
    baseurl: https://sourceforge.net/projects/turbovnc/files
    gpgcheck: yes
    gpgkey: http://pgp.mit.edu/pks/lookup?op=get&search=0x6BBEFA1972FEB9CE
    enabled: yes

- name: install turbovnc
  yum:
    name: turbovnc
    state: installed

- name: turbovnc sysconfig
  template:
    src: etc/sysconfig/tvncservers.j2
    dest: /etc/sysconfig/tvncservers
    owner: root
    group: root
    mode: 0644

- name: turbovnc passwd dir
  file:
    path: "/home/{{ ansible_user }}/.vnc/"
    state: directory
    mode: "u+rwx"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: turbovnc passwd
  copy:
    src: "home/user/.vnc/passwd"
    dest: "/home/{{ ansible_user }}/.vnc/passwd"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
    directory_mode: 0600

- name: enable tvncserver service
  service:
    name: tvncserver
    enabled: yes
    state: started
