---
# handlers file for chess-fracture

- name: restart tvncserver
  service:
    name: tvncserver
    state: restarted

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: systemctl daemon-reload
  command: systemctl daemon-reload

