---


- name: install python36
  yum:
    name: "{{item}}"
    state: installed
    enablerepo: epel-testing
  with_items:
    - python-virtualenv
    - python36
    - uwsgi
    - uwsgi-plugin-python36

- name: django venv
  pip:
    virtualenv: "{{django_venv_path}}"
    virtualenv_python: python36
    requirements: "/home/{{ chessfracture_user }}/chessfracture/django/requirements.txt"
  become_user: "{{ chessfracture_user }}"

- name: configure uwsgi
  template:
    src: etc/uwsgi.ini
    dest: /etc/uwsgi.ini
  notify: restart uwsgi

- name: chessfracture-db hosts
  lineinfile:
    path: /etc/hosts
    regexp: chessfracture-db
    line: "{{ansible_host}} chessfracture-db"
  notify: restart uwsgi

- name: create /tmp/blender
  file:
    path: /tmp/blender
    state: directory
    mode: 0755
    owner: "{{ chessfracture_user }}"
    group: "{{ chessfracture_user }}"

- name: start uwsgi
  service:
    name: uwsgi
    state: started
    enabled: true
