---
# tasks file for chessfracture
- name: test connection
  ping:

- name: install requirements
  yum:
    name:
      - yum-utils
      - zip
      - xorg-x11-server-Xorg
      - xorg-x11-xauth
      - xorg-x11-server-utils
      - mesa-dri-drivers
      - git
      - python2-pip
      - gcc
      - openssl-devel
      - vim

- name: docker
  include: docker.yml

- name: sync files
  synchronize:
    src: "{{ playbook_dir }}/.."
    dest: "/home/{{ chessfracture_user }}/chessfracture"
  become_user: "{{ chessfracture_user }}"
  notify: restart uwsgi


- name: turbovnc
  include: turbovnc.yml

- name: reverse proxy
  include: nginx.yml

- name: blender
  include: blender.yml

- name: postgres
  include: postgres.yml

- name: django
  include: django.yml

