---

- name: install rust
  shell: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
  args:
    creates: "/home/{{ ansible_user }}/.cargo/bin/cargo"
    warn: false
  become_user: "{{ ansible_user }}"

- name: build webapp
  command: /home/ansible/.cargo/bin/cargo build
  args:
    chdir: "/home/{{ ansible_user }}/chessfracture/webapp"
    creates: "/home/{{ ansible_user }}/chessfracture/webapp/target/"
  become_user: "{{ ansible_user }}"
  notify: restart webapp

- name: copy webapp startup script
  template:
    src: usr/lib/systemd/system/webapp.service.j2
    dest: /usr/lib/systemd/system/webapp.service
  notify: systemctl daemon-reload

- name: force handlers
  meta: flush_handlers

- name: start webapp
  service:
    name: webapp
    state: started
    enabled: yes

- name: create app dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items:
    - /pgn
    - /blend

- name: add /blend purge
  template:
    src: etc/cron.d/purge_blend.j2
    dest: /etc/cron.d/purge_blend.j2

