---
# handlers file for docker-chess-fracture
- name: restart docker
  service:
    name: docker
    state: restarted

- name: restart tvncserver
  service:
    name: tvncserver
    state: restarted

- name: rebuild webapp
  command: /home/ansible/.cargo/bin/cargo build
  args:
    chdir: "/home/{{ ansible_user }}/docker-chess-fracture/webapp"
  become_user: "{{ ansible_user }}"

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: systemctl daemon-reload
  command: systemctl daemon-reload

- name: restart webapp
  service:
    name: webapp
    state: restarted
