---
# tasks file for chessfracture-web

- name: reverse proxy
  include: nginx.yml

- name: postgres
  include: postgres.yml

- name: django
  include: django.yml

- name: configure uwsgi
  template:
    src: etc/uwsgi.ini
    dest: /etc/uwsgi.ini
  notify: restart uwsgi

- name: start uwsgi
  service:
    name: uwsgi
    state: restarted
    enabled: true
