---
# tasks file for chessfracture-web

- name: install uwsgi
  yum:
    name:
      - uwsgi
      - uwsgi-plugin-python36
      - uwsgi-logger-file
    state: installed
    enablerepo: epel-testing

- name: configure uwsgi
  template:
    src: etc/uwsgi.ini
    dest: /etc/uwsgi.ini
  notify: restart uwsgi

- name: reverse proxy
  include: nginx.yml

- name: postgres
  include: postgres.yml

- name: django
  include: django.yml

- name: prometheus
  include: prometheus.yml

- name: grafana
  include: grafana.yml

  #- meta: flush_handlers

- name: start uwsgi
  service:
    name: uwsgi
    state: started
    enabled: true
