---
# tasks file for chessfracture-web

- name: reverse proxy
  include: nginx.yml

- name: postgres
  include: postgres.yml

- name: django
  include: django.yml

- name: install uwsgi
  yum:
    name: "{{item}}"
    state: installed
    enablerepo: epel-testing
  with_items:
    - uwsgi-plugin-python36
    - uwsgi

- name: configure uwsgi
  template:
    src: etc/uwsgi.ini
    dest: /etc/uwsgi.ini
  notify: restart uwsgi

  #- meta: flush_handlers

- name: start uwsgi
  service:
    name: uwsgi
    state: started
    enabled: true
