---

- name: install nginx
  yum:
    name: nginx
    state: installed

- name: nginx service
  service:
    name: nginx
    state: started
    enabled: true

- name: open port 80
  firewalld:
    port: 80/tcp
    permanent: true
    immediate: true
    state: enabled

- name: configure nginx.conf
  template:
    src: etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: configure nginx webapp.conf
  template:
    src: "etc/nginx/conf.d/{{item}}.conf"
    dest: "/etc/nginx/conf.d/{{item}}.conf"
  notify: restart nginx
  with_items:
    - default
    - django

- name: disable selinux # FIXME
  selinux:
    policy: targeted
    state: permissive

- name: create /var/www/media
  file:
    path: /var/www/media
    state: directory
    mode: 0755
    owner: root
    group: root

- name: copy media to /var/www/media
  synchronize:
    src: media/
    dest: /var/www/media
    delete: yes
