---

- name: install nginx
  yum:
    name: nginx
    state: installed

- name: nginx service
  service:
    name: nginx
    state: started
    enabled: true

- name: open port 80
  firewalld:
    port: 80/tcp
    permanent: true
    immediate: true
    state: enabled

- name: configure nginx.conf
  template:
    src: etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: configure nginx webapp.conf
  template:
    src: etc/nginx/conf.d/webapp.conf
    dest: /etc/nginx/conf.d/webapp.conf
  notify: restart nginx

- name: disable selinux # FIXME
  selinux:
    policy: targeted
    state: permissive

- name: copy /static
  synchronize:
    src: static/
    dest: /static
    delete: yes
