---

- name: add postgres repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm
    state: installed

- name: install postgres
  yum:
    name: "{{item}}"
    state: installed
  with_items:
    - python-psycopg2
    - postgresql10
    - postgresql10-server

- name: init postgres
  command: /usr/pgsql-10/bin/postgresql-10-setup initdb
  args:
    creates: /var/lib/pgsql/10/data/

- name: postgresql-10 service
  service:
    name: postgresql-10
    state: started
    enabled: true

#https://github.com/ansible/ansible-examples/blob/master/language_features/postgresql.yml
- name: create db
  postgresql_db:
    name: chessfracture
    encoding: UTF-8
  become_user: postgres

- name: create postgres user
  postgresql_user:
    db: chessfracture
    name: chessfracture
    password: nopasswd
  become_user: postgres

      #- name: open port 80
      #  firewalld:
      #    port: 80/tcp
      #    permanent: true
      #    immediate: true
      #    state: enabled

