---
# handlers file for chessfracture

- name: systemctl daemon-reload
  command: systemctl daemon-reload

- name: restart tvncserver
  service:
    name: tvncserver
    state: restarted

- name: restart chessfracture.worker
  service:
    name: "chessfracture.worker@{{ item }}"
    state: restarted
  with_sequence: count={{ansible_processor_cores}}
