---

- name: create /etc/sysconfig/systemd/system
  file:
    path: /etc/sysconfig/systemd/system
    state: directory

- name: create systemd service
  template:
    src: etc/sysconfig/systemd/system/chessfracture.worker.service
    dest: /etc/sysconfig/systemd/system/chessfracture.worker.service
  notify:
    - systemctl daemon-reload
    - restart chessfracture.worker
