---

- name: add turbovnc repo
  yum_repository:
    name: TurboVNC
    description: TurboVNC official RPMs
    baseurl: https://sourceforge.net/projects/turbovnc/files
    gpgcheck: yes
    gpgkey: https://www.turbovnc.org/key/VGL-GPG-KEY
    #gpgkey: http://pgp.mit.edu/pks/lookup?op=get&search=0x6BBEFA1972FEB9CE
    enabled: yes

- name: install turbovnc
  yum:
    name: turbovnc
    state: installed

- name: turbovnc sysconfig
  template:
    src: etc/sysconfig/tvncservers.j2
    dest: /etc/sysconfig/tvncservers
    owner: root
    group: root
    mode: 0644
  notify: restart tvncserver

- name: turbovnc passwd dir
  file:
    path: "/home/{{ chessfracture_user }}/.vnc/"
    state: directory
    mode: "u+rwx"
    owner: "{{ chessfracture_user }}"
    group: "{{ chessfracture_user }}"

    #- name: turbovnc passwd
    #  copy:
    #    src: "home/user/.vnc/passwd"
    #    dest: "/home/{{ ansible_user }}/.vnc/passwd"
    #    owner: "{{ ansible_user }}"
    #    group: "{{ ansible_user }}"
    #    mode: 0600
    #    directory_mode: 0600
    #  notify: restart tvncserver

- name: turbovnc passwd
  shell: 'umask 077; echo mypassword | /opt/TurboVNC/bin/vncpasswd -f > /home/{{ chessfracture_user }}/.vnc/passwd'
  args:
    creates: "/home/{{ chessfracture_user }}/.vnc/passwd"
  become_user: "{{ chessfracture_user }}"
  notify: restart tvncserver

- name: enable tvncserver service
  service:
    name: tvncserver
    enabled: yes
    state: started
